env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

gomod:
  proxy: true

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: packages
    homepage:  https://goreleaser.com
    description: Deliver Go binaries as fast and easily as possible
    maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
    license: MIT
    vendor: GoReleaser
    contents:
      - src: ./completions/goreleaser.bash
        dst: /etc/bash_completion.d/goreleaser
      - src: ./completions/goreleaser.fish
        dst: /usr/share/fish/completions/goreleaser.fish
      - src: ./completions/goreleaser.zsh
        dst: /usr/local/share/zsh/site-functions/_goreleaser
    formats:
    - apk
    dependencies:
    - git
    recommends:
    - golang     

dockers:
- image_templates:
  - 'goreleaser:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  exporter: tarDockerFormat  
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/amd64"
  extra_files:
  - scripts/entrypoint.sh
- image_templates:
  - 'goreleaser:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--platform=linux/arm64"
  goarch: arm64
  extra_files:
  - scripts/entrypoint.sh
